name: CI
on: [push]
jobs:
  build:
    name: Build, lint, and test on Node ${{ matrix.node }} and ${{ matrix.os }} and ${{ matrix.target}}

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ['14.x', '16.x']
        os: [ubuntu-latest]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Install deps and build (with cache) server
        uses: bahmutov/npm-install@v1
        with:
          working-directory: ./server

      - name: Lint server
        run: yarn lint
        working-directory: ./server

      - name: Build server
        run: yarn build
        working-directory: ./server

      - name: Test server
        run: yarn test --ci --coverage --maxWorkers=2
        working-directory: ./server

      - name: Install deps and build (with cache) middleware
        uses: bahmutov/npm-install@v1
        with:
          working-directory: ./middleware

      - name: Lint middleware
        run: yarn lint
        working-directory: ./middleware

      - name: Build middleware
        run: yarn build
        working-directory: ./middleware

      - name: Test middleware
        run: yarn test --ci --coverage --maxWorkers=2
        working-directory: ./middleware

